Always render actions from center of the `child`
rasitayaz/flutter-pie-menu pull request #52
Opened 2024-02-22 08:53 UTC by sadespresso

Fixes #50

This PR adds `alwaysPlaceActionFromCenter` option to `PieTheme`, default to `false`. When set to `true` forces `PieMenu` to be rendered from the center of the `child`. Especially useful when using `PieMenu` with small buttons, such as `FloatingActionButton`.

When `alwaysPlaceActionFromCenter = false`:
![image](https://github.com/rasitayaz/flutter-pie-menu/assets/51638223/265ad4ac-4871-491a-8ab1-2651db8ee0a9)
![image](https://github.com/rasitayaz/flutter-pie-menu/assets/51638223/61ca3bf5-3015-4860-947a-646f8f988329)

When `alwaysPlaceActionFromCenter = true`:
![image](https://github.com/rasitayaz/flutter-pie-menu/assets/51638223/2a39755a-a8f5-40a3-adfa-28872771e8bf)

**Not a breaking change**, everything will continue to work as before

Tested on Android, iOS, Linux

2024-03-06 02:00 UTC, NewbieJess13 commented
This is what I need for my project, For now I used @sadespresso fork and hopefully merged with the package. Thank you @rasitayaz & @sadespresso!!

2024-04-12 15:00 UTC, rasitayaz requested changes
Thank you for the contribution, sorry I haven't got the time to review this. I have one suggestion;

We should set `_pointerOffset` to the center of the child inside `attachMenu` method instead of introducing a `_menuCenter` getter and modifying `_getActionOffset`. This would minimize the amount of changes in `PieCanvasCore` and maintain consistency. No changes will be required for `PieDelegate` as well.

2024-04-12 15:50 UTC, sadespresso commented
Okay, lemme do that and send you review request again :D :D

2024-04-12 16:55 UTC, sadespresso commented on lib/src/pie_canvas_core.dart
> +          ? (hoveredAction != null)
I'm little unsure about what troubles it could cause later...

Shouldn't affect when `alwaysPlaceActionFromCenter` is false

2024-04-12 16:58 UTC, sadespresso commented
So, I've updated the code per your recommendations, and they look quite great!

When `alwaysPlaceActionFromCenter` is true, the `attachMenu` sets `_pointerOffset`.

Upon pointer up, it "forces" the menu to stay open when there's no hovered action. See my review comment to see the code

2024-04-12 17:21 UTC, sadespresso commented on lib/src/pie_canvas_core.dart
> +          ? (hoveredAction != null)
Now when the pointer leaves the menu widget, it dismisses.

Uses `RenderBox.hitTest()`

2024-04-12 17:24 UTC, sadespresso commented
Tested, and confirmed that the new implementation works the same as before.

2024-04-12 19:28 UTC, rasitayaz commented
what's the purpose of hit test?

2024-04-13 04:19 UTC, sadespresso commented
Because _pointerOffset is artificially moved to the center of the menu button, it makes '_isBeyondPointerBounds' behave incorrectly.

As I understand, a simple tap should leave the menu open. A drag triggers action only if the pointer is on the action, and dismissed the menu otherwise.

Putting hit test on the menu button ensures the behaviors mentioned above to work correctly.

Now that I think about it, it also might be possible to just pass modified offset to '_isBeyondPointerBounds'

2024-04-13 04:20 UTC, sadespresso commented
I can give you more details answer when I get home 😃

2024-04-13 04:23 UTC, sadespresso commented
If we remove the hit test, a simple tap will just dismiss the menu, and dragging to an action will not trigger the action; requiring an additional tap. which i believe, isn't the expected behavior

Instead of hit test, we can get the original pointer position and do distance check like one in the _isBeyondPointerBounds

2024-04-17 18:00 UTC, rasitayaz commented
thank you, I'll take it from here. I might introduce alignment and offset variables instead of `alwaysPlaceActionFromCenter` to expand this feature.

2024-04-17 18:00 UTC, merged